apiVersion: v1
kind: Service
metadata:
  name: health-risk-service
spec:
  type: NodePort
  selector:
    app: health-risk
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
