name: Train Model

on:
  push:
    branches:
      - dev

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install Flask scikit-learn pandas numpy pytest joblib
      - name: Train Model
        run: python src/train.py
